language: objective-c

before_install:
    - gem install cocoapods -v 0.29.0 --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty -v 0.1.4 --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail && xcodebuild -workspace PushTest.xcworkspace -scheme PushTest -sdk iphonesimulator -configuration Release clean build | xcpretty -c

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
